import {LoginResponseType} from "../../dal/api";

export enum ActionTypes {
    SET_STATUS = 'APP/SET-STATUS',
    INITIALIZED_SUCCESS = 'APP/INITIALIZED_SUCCESS',
    SET_USER_DATA = 'LOGIN/SET_USER_DATA',
    IS_AUTH = 'LOGIN/IS_AUTH',
    UPDATE_PROFILE = 'LOGIN/UPDATE_PROFILE',
    LOGOUT = 'LOGOUT/LOGOUT_USERS',
    USER_REGISTER = 'REGISTRATION/USER_REGISTER',
    USER_REGISTER_ERROR = 'REGISTRATION/USER_REGISTER_ERROR',
    USER_REGISTER_STATUS = 'REGISTRATION/USER_REGISTER_STATUS',
    GET_PACKS = 'PACKS/GET_PACKS',
    SET_PACKS = 'PACKS/SET_PACKS',
    UPDATE_PACKS = 'PACKS/UPDATE_PACKS',
    LOADING_PACKS = 'PACKS/LOADING_PACKS',
    DELETE_PACKS = 'PACKS/DELETE_PACKS',
    GET_CARDS = 'CARDS/GET_CARDS',
    SET_CARDS = 'CARDS/SET_CARDS',
    UPDATE_CARDS = 'CARDS/UPDATE_CARDS',
    DELETE_CARDS = 'CARDS/DELETE_PACKS',
}


