export enum ActionTypes {
    SET_STATUS = 'APP/SET-STATUS',
    SET_ERROR = 'APP/SET_ERROR',
    INITIALIZED_SUCCESS = 'APP/INITIALIZED_SUCCESS',
    SET_USER_DATA = 'LOGIN/SET_USER_DATA',
    IS_AUTH = 'LOGIN/IS_AUTH',
    UPDATE_PROFILE = 'LOGIN/UPDATE_PROFILE',
    USER_REGISTER = 'REGISTRATION/USER_REGISTER',
    IS_FORGOT_PASS = 'FORGOT_PASSWORD/IS_FORGOT_PASS',
    SET_PACKS = 'PACKS/SET_PACKS',
    CREATE_PACKS = 'PACKS/CREATE_PACKS',
    SET_CURRENT_PAGE = 'PACKS/SET_CURRENT_PAGE',
    SET_PACKS_TOTAL_COUNT = 'PACKS/SET_PACKS_TOTAL_COUNT',
    GET_CARDS = 'CARDS/GET_CARDS',
    SET_CARDS = 'CARDS/SET_CARDS',
    UPDATE_CARDS = 'CARDS/UPDATE_CARDS',
    DELETE_CARDS = 'CARDS/DELETE_PACKS',
}


